version: "3.8"

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - "5000:5000"

  frontend:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    depends_on:
      - backend
    ports:
      - "3000:3000"
  
  gym_app_sql:
    image: mysql:5.7
    container_name: gym_app_sql
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: app_db
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - shared-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: gym_app_pma
    links:
      - gym_app_sql
    environment:
      PMA_HOST: gym_app_sql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - shared-network

networks:
  shared-network:
volumes:
  dbdata: 